apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.name }}
spec:
  selector:
    app: {{ .Values.api.name }}
  ports:
  - protocol: TCP
    port: {{ .Values.api.port }}
    targetPort: {{ .Values.api.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.web.name }}
spec:
  selector:
    app: {{ .Values.web.name }}
  ports:
  - protocol: TCP
    port: {{ .Values.web.port }}
    targetPort: {{ .Values.web.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.web.name }}-nodeport
spec:
  selector:
    app: {{ .Values.web.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.web.port }}
      targetPort: {{ .Values.web.containerPort }}
      nodePort: {{ .Values.web.nodePort }}
  type: NodePort
